apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pygitserver.fullname" . | lower }}-config
  labels:
    {{- include "pygitserver.labels" . | nindent 4 }}
data:
  conf.yaml: |
    server:
      host: "0.0.0.0"
      port: {{ .Values.service.port }}
    repositories:
{{- range .Values.repositories }}
      - name: "{{ .name }}"
        path: "/git/repos/{{ .name }}.git"
{{- if .init_from }}
        init_from: "{{ .init_from }}"
{{- end }}
{{- end }}