apiVersion: v1
kind: Service
metadata:
  name: {{ include "pygitserver.fullname" . | lower }}
  labels:
    {{- include "pygitserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pygitserver.selectorLabels" . | nindent 4 }}